const modules=[
['Modulo-1-Excel.png','Módulo 01 - Introdução','Nesse módulo você vai aprender os conceitos fundamentais do Excel, como abrir e salvar pastas de trabalho, entender células e referências, aplicar fórmulas básicas e usar operadores matemáticos. É o ponto de partida ideal para dominar o programa desde o início.','09 aulas • 01 hora, 18 minutos e 37 segundos'],
['Modulo-2-Excel.png','Módulo 02 - Formatação de Células','Nesse módulo você vai descobrir como deixar suas planilhas muito mais organizadas e profissionais, aprendendo a usar formatação de números, alinhamento, fontes, bordas, estilos e formatação condicional para destacar informações importantes.','08 aulas • 51 minutos e 44 segundos'],
['Modulo-3-Excel.png','Módulo 03 - Gráficos e Referências','Nesse módulo você vai aprender a criar e personalizar gráficos do zero, trabalhar com mini gráficos e dominar o uso de referências absolutas e cruzadas entre planilhas, tornando suas análises visuais e automatizadas.','05 aulas • 44 minutos e 50 segundos'],
['Modulo-4-Excel.png','Módulo 04 - Funções','Nesse módulo você vai dominar as principais funções do Excel — como SE, CONT.SE, SOMASE e PROCV — entendendo na prática como aplicá-las para automatizar cálculos e aumentar a produtividade nas suas planilhas.','07 aulas • 01 hora, 48 minutos e 7 segundos'],
['Modulo-5-Excel.png','Módulo 05 - Validação de Dados e Configurações Finais','Nesse módulo final você vai aprender a proteger suas planilhas, validar dados e ajustar o layout da página para impressão, garantindo um resultado profissional e funcional.','03 aulas • 31 minutos e 42 segundos']];
document.querySelector('#modules').innerHTML=modules.map(m=>`<article class="module"><img src="https://plrprofissional.com/wp-content/uploads/2025/10/${m[0]}" alt="${m[1]}"><div><h3>${m[1]}</h3><p>${m[2]}</p><b>${m[3]}</b></div></article>`).join('');
const faq=[['O que é isso tudo?','É um curso em vídeo aulas exclusivo para quem quer aprender todas as técnicas e os principais comandos para dominar o Excel e colocar seu negócio em ordem, ser promovido ou passar em qualquer processo seletivo.'],['Para quem é isso?','Para quem busca emprego, recolocação, promoção, mais organização, produtividade e capacidade de tirar projetos do papel usando Excel.'],['Quanto tempo até começar a ver os resultados?','Quanto antes você colocar em prática o que está no curso, mais rápido poderá aprender. As informações dependem de execução e consistência.'],['Como este guia é entregue?','Logo após a confirmação do pagamento você recebe no seu e-mail os dados de acesso do curso. Pagamentos por boleto podem levar até 3 dias úteis para compensação.'],['Por que preciso comprar esse guia?','Para “cortar caminho” saindo do zero absoluto e chegar ao nível profissional com um treinamento estruturado.'],['Quanto custa?','O valor apresentado nesta página é R$ 97,00 à vista ou 12x de R$ 5,58.'],['Existe uma garantia?','Sim. A página original informa garantia de 7 dias para solicitar reembolso caso você não fique satisfeito.']];
document.querySelector('#faq').innerHTML=faq.map(([q,a])=>`<div class="faq-item"><button class="faq-q">${q}</button><div class="faq-a"><p>${a}</p></div></div>`).join('');
document.addEventListener('click',e=>{if(e.target.classList.contains('faq-q'))e.target.parentElement.classList.toggle('open');if(e.target.closest('[data-empty-checkout]')){e.preventDefault();alert('Adicione o link do checkout no arquivo index.html antes de publicar.');}});
